data:
  corpus:                                 # Pass to dataloader
    # The following depends on corpus
    path: '/data/storage/harry/LibriSpeech'
    name: 'LibriSpeech'
    dev_split: ['LibriSpeech', 'dev-clean', 'dev']
    test_split: ['LibriSpeech', 'test-clean', 'test']
    bucketing: False
    batch_size: 1
src:
  config: '/data/storage/harry/End-to-end-ASR-Pytorch/config/librispeech_asr.yaml'
  ckpt: '/data/storage/harry/E2E_ASR/ckpt/LS100_JOINT_0/best_att_LibriSpeech.pth'

decode:
  ctc_weight: 0
  beam_size: 8
  # vocab_candidate: 12
  min_len_ratio: 0.01
  max_len_ratio: 0.25
  lm_config: '/data/storage/harry/End-to-end-ASR-Pytorch/config/librispeech_lm.yaml'
  lm_path: '/data/storage/harry/E2E_ASR/ckpt/RNNLM_LS100_TEST_0/best_ppx.pth'
  lm_weight: 0.3